services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: paperplane-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./airplane.db
      - MAIL_SMTP_HOST=smtp.yandex.ru
      - MAIL_SMTP_PORT=465
      - MAIL_SMTP_USERNAME=ethernet11.11@yandex.ru
      - MAIL_SMTP_PASSWORD=uiphoizedpycpqgm
      - MAIL_FROM_EMAIL=ethernet11.11@yandex.ru
      - MAIL_FROM_NAME=Paper Plane
      - MAIL_SMTP_STARTTLS=false
      - MAIL_SMTP_USE_SSL=true
      - MAIL_RAISE_ON_ERROR=true
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paperplane-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped